defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hyperparams:
  lr: 1e-6
  epochs: 10

core:
  device: "cuda"
  train: false
  inference: false

files:
  root_dir: "data/"
  data_dir: "data/data"
  train: "train"
  val: "val"
  test: "test"
  file_ext: ".csv"