defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hyperparams:
  lr: 3e-4
  epochs: 10
  batch_size: 32

core:
  device: "cuda"
  train: false
  inference: false
  pretrained: false

files:
  root_dir: "data/"
  data_dir: "data/data"
  models_dir: "models/"
  train: "train"
  val: "val"
  test: "test"
  file_ext: ".csv"
